namespace BL.Servers.CR.Logic.Enums
{
    public enum Gamefile
    {
        Abilities = 1,
        Achievements = 2,
        Alliance_Badge = 3,
        Alliance_Roles = 4,
        Area_Effect_Objects = 5,
        Areans = 6,
        Buildings = 7,
        Character_Buffs = 8,
        Characters = 9,
        Chest_Order = 10,
        Configuration_Definitions = 11,
        Content_Tests = 12,
        Decos = 13,
        Draft_Deck = 14,
        Event_Categories = 15,
        Event_Category_Defintions = 16,
        Event_Category_Enums = 17,
        Event_Category_Object_Definitions = 18,
        Exp_Levels = 19,
        Gamble_Chests = 20,
        Game_Modes = 21,
        Globals = 22,
        Heroes = 23,
        Locales = 24,
        Locations = 25,
        NPCS = 26,
        Predefined_Decks = 27,
        Projectiles = 28,
        Rarities = 29,
        Regions = 30,
        Resource_Packs = 31,
        Resources = 32,
        Shop = 33,
        Spell_Sets = 34,
        Spells_Buildings = 35,
        Spells_Characters = 36,
        Spells_Heroes = 37,
        Spells_Others = 38,
        Survival_Modes = 39,
        Taunts = 40,
        Tournament_Tiers = 41,
        Treasure_Chests = 42,
        Tutorials_Home = 43,
        Tutorials_NPC = 44
    }
}