//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Servers.CoC.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        public long ID { get; set; }
        public string Data { get; set; }
    }
}
